### ISSUE TITLE
Update shut down instructions

### ISSUE THREAD

**Issue by adammwilson** [BioSCape-io/BioSCape-SMCE-User-Guide#2]
[Current instructions](https://bioscape-smce-user-guide.readthedocs.io/en/latest/pages/introduction.html#shutting-down-servers-and-logging-out) say:

> In the top-right of the Jupyter interface, go to “File → Hub Control Panel”. This will open a new tab.

But this option is not available.  Instead, I think it should say something like:

> Click the icon in the very upper left of the window (to the left of the 'File' menu) to open a new tab: 
<img width="293" alt="image" src="https://github.com/EvanDLang/BioSCape-SMCE-User-Guide/assets/900623/bd612149-1dc7-4f8f-b2d5-3f7d4bf85b07">

@EvanDLang

**Comment by EvanDLang** [comment]
Yep, there are still a few things that are from the SHIFT SMCE and are incorrect for this environment. I am working on changing them.

**Comment by EvanDLang** [comment]
Docs are updated.
